### ISSUE TITLE
notify conf isnt loading 

### ISSUE THREAD

**Issue by Nithissh0708** [projectdiscovery/notify#54]
hi team ,
i had been running as a root and i cameup with this error

Running as root, skipping config file write to avoid permissions issues: /root/.config/notify/notify.conf
Could not read configuration file /root/.config/notify/notify.conf - ignoring error: open /root/.config/notify/notify.conf: no such file or directory

**Comment by daffainfo** [comment]
Me too! im running notify in vps as root, so I got this error

**Comment by parrasajad** [comment]
@Nithissh0708 @daffainfo Thank you for reporting this issue, It is already fixed in `dev` branch and will be merged soon

You can fetch the `dev` version by `GO111MODULE=on go get -v github.com/projectdiscovery/notify/cmd/notify@dev`
Caution:  `dev` may not always be stable

**Comment by sh0tal** [comment]
Hello guys,
I run to a slightly different problem.
As i installed notify and runt it as root, i got this message:

```
Running as root, skipping config file write to avoid permissions issues: /root/.config/notify/notify.conf
Could not read configuration file /root/.config/notify/notify.conf - ignoring error: open /root/.config/notify/noti
fy.conf: no such file or directory
```
Then proceeded to run it as a normal user 
and i got this message:
```
Found existing config file: /home/alexiscostoulas/.config/notify/notify.conf
Could not read configuration file /home/alexiscostoulas/.config/notify/notify.conf - ignoring error: EOF
```


Then i copied the files to the root directory: /root/.config/notify/
And run it again.
The message i got is this one:
```
Found existing config file: /root/.config/notify/notify.conf
Could not read configuration file /root/.config/notify/notify.conf - ignoring error: EOF
```

what is the problem and it cannot read the configuration file?

**Comment by sh0tal** [comment]
Hello guys,
I run to a slightly different problem.
As i installed notify and runt it as root, i got this message:

```
Running as root, skipping config file write to avoid permissions issues: /root/.config/notify/notify.conf
Could not read configuration file /root/.config/notify/notify.conf - ignoring error: open /root/.config/notify/noti
fy.conf: no such file or directory
```
Then proceeded to run it as a normal user 
and i got this message:
```
Found existing config file: /home/user/.config/notify/notify.conf
Could not read configuration file /home/user/.config/notify/notify.conf - ignoring error: EOF
```


Then i copied the files to the root directory: /root/.config/notify/
And run it again.
The message i got is this one:
```
Found existing config file: /root/.config/notify/notify.conf
Could not read configuration file /root/.config/notify/notify.conf - ignoring error: EOF
```

what is the problem and it cannot read the configuration file?

**Comment by parmanand99** [comment]
Still the same problem:
[FTL] Could not create runner: could not open provider config file: open /home/user/.config/notify/provider-config.yaml: no such file or directory

**Comment by theeldruin** [comment]
I had the same problem. I solved checking the identation on provider-config.yaml
The correct is 2 spaces, not tabs
